### ISSUE TITLE
Compatibility issue with python 3.12 - getting dataclass error 

### ISSUE THREAD

**Issue by SridharRG** [ocell/mapsy#2]
First of all this is an amazing project as a python and GIS lover.

I faced difficulty in running the basic python script and while searching for error I get to see this is GenAI(s) response: The issue lies in the use of a mutable default in a @dataclass within the mapsy library. Python 3.12 enforces stricter rules for @dataclass fields. Mutable defaults like objects (e.g., Color) must use a default_factory instead of directly assigning the default.

A quick fix in this would me much appreciated. 
Thank you.

**Comment by felix-ht** [comment]
Thanks for the input, might setup tox to check against all supported versions.

**Comment by SridharRG** [comment]
Thanks for looking into it. Happy to look forward to this patch.

**Comment by felix-ht** [comment]
fixed with https://github.com/ocell/mapsy/releases/tag/v0.3.0

**Comment by SridharRG** [comment]
Thanks a lot.
